server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  #############################新增网关配置###########################
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/company/**         # 断言，路径相匹配的进行路由
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
####################################################################

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://sujunbin:sujunbin@eureka7001.com:7001/eureka,http://sujunbin:sujunbin@eureka7002.com:7002/eureka
    instance:
      instance-id: geteway-9527
      prefer-ip-address: true
